### ISSUE TITLE
Improve project security

### ISSUE THREAD

**Issue by scott-wilson** [scott-wilson/checks#22]
- [ ] Set up security policy
- [ ] Enable vulnerability reporting
- [ ] Set up code scanning on GitHub
- [ ] Set up secret scanning alerts
- [ ] Have security db scanner CI jobs run on a daily or weekly basis (for example, `cargo-audit`)
